<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>FAI {{ $header['work_id'] }}</title>
    <style>
        @page {
            margin: 30px 18px 22px 18px;
        }

        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            color: #111;
            font-size: 11px;
        }

        /* Encabezado */
        .h1 {
            font-size: 16px;
            font-weight: 700;
            margin: 0 0 6px;
        }

        .small {
            font-size: 10px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta td {
            padding: 4px 6px;
            border: 1px solid #333;
        }

        /* Tabla de datos */
        .grid {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .grid thead th {
            background: #f1f1f1;
            font-weight: 700;
            border: 1px solid #333;
            padding: 6px 6px;
        }

        .grid td {
            border: 1px solid #333;
            padding: 5px 6px;
            vertical-align: top;
        }

        .center {
            text-align: center;
        }

        .w-date {
            width: 9%;
        }

        .w-type {
            width: 8%;
        }

        .w-op {
            width: 9%;
        }

        .w-operator {
            width: 8%;
        }

        .w-results {
            width: 7%;
        }

        .w-sbis {
            width: 10%;
        }

        .w-obs {
            width: 18%;
        }

        .w-station {
            width: 7%;
        }

        .w-method {
            width: 8%;
        }

        .w-inspector {
            width: 8%;
        }

        /* Repetir thead en cada página */
        thead {
            display: table-header-group;
        }

        tfoot {
            display: table-row-group;
        }

        tr {
            page-break-inside: avoid;
        }

        /* Estilo “input” visual como tu UI */
        .cellbox {
            background: #f7f9fb;
            border: 1px solid #d7dde5;
            padding: 3px 5px;
            border-radius: 3px;
        }
    </style>
</head>

<body>

    {{-- Encabezado --}}
    <table class="meta" style="margin-bottom:8px;">
        <tr>
            <td>
                <div class="h1">FAI / IPI Inspection</div>
                <div class="small">Generated by Inspection</div>
            </td>
            <td colspan="2">
                <div class="h1">WO# {{ $header['work_id'] }} </div>
                <div class="h2">PN: {{ $header['pn'] }}</div>
            </td>
            <td colspan="2"> {{ $header['description'] }}</td>
            <td><strong>CUST: </strong>{{ $header['costumer'] }}</td>
            <td colspan="2">
                <div class="small"><strong>Printed: </strong>{{ $generatedAt->format('m/d/Y') }} {{-- o m/d/Y h:i A --}}</div>
                <div><strong>Rise: </strong>{{ \Carbon\Carbon::now()->format('m/d/Y') }}</div>
            </td>

        </tr>
        <tr>
            <td colspan="2"><strong>CO QTY:</strong> {{ $header['qty'] }}</td>
            <td colspan="2"><strong>DUE DATE:</strong> {{ $header['due_date'] ? \Carbon\Carbon::parse($header['due_date'])->format('m/d/Y') : '' }}</td>
            <td><strong>CO#:</strong> {{ $header['co'] }}</td>
            <td><strong>CUST PO#:</strong> {{ $header['cust_po'] }}</td>
            <td><strong>WO QTY#:</strong> {{ $header['wo_qty'] }}</td>
            <td><strong>QC INSP PACKET</strong></td>
        </tr>

    </table>
    <table style="width:100%; border-collapse:separate; border-spacing:0;">
        <tr>
            <td style="border:0; padding:2px 0;">
                <strong>{{ $header['location'] }}</strong> {{ $header['qty'] }} SAMPLING:

            </td>
        </tr>
        <tr>
            <td style="border:0; padding:2px 0;">
                <strong>DELIVER</strong> {{ $header['qty'] }} PIECES BY:
                {{ !empty($header['due_date']) ? \Carbon\Carbon::parse($header['due_date'])->format('m/d/Y') : '' }}
            </td>
        </tr>
        <tr>
            <td style="border:0; padding:2px 0;">
                <strong>Unless otherwise stated, tolerance:</strong>
                &nbsp;.x±_______________ &nbsp; .xx±_______________ &nbsp; .xxx±_______________&nbsp; .xxxxx±_______________ &nbsp; ±_______________ Degree
            </td>
        </tr>
    </table>
    {{-- Tabla de filas UNO A UNO --}}
    <table class="grid">
        <thead>
            <tr>
                <th class="center w-date">DATE</th>
                <th class="center w-type">INSP TYPE</th>
                <th class="center w-op">OPERATION</th>
                <th class="center w-operator">OPERATOR</th>
                <th class="center w-results">RESULTS</th>
                <th class="center w-sbis">SB/IS</th>
                <th class="center w-obs">OBSERVATION</th>
                <th class="center w-station">STATION</th>
                <th class="center w-method">METHOD</th>
                <th class="center w-inspector">INSPECTOR</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $r)
            <tr>
                <td class="center">{{ \Carbon\Carbon::parse($r->date)->format('m/d/Y') }}</td>
                <td class="center">{{ strtoupper($r->insp_type) }}</td>
                <td class="center">{{ $r->operation }}</td>
                <td class="center break">{{ $r->operator ?? '' }}</td>
                <td class="center">
                    @php $res = strtolower((string)$r->results); @endphp
                    {{ $res === 'pass' ? 'Pass' : ($res === 'fail' ? 'Fail' : strtoupper($r->results)) }}
                </td>
                <td class="">{{ $r->sb_is }}</td>
                <td class="">{{ $r->observation }}</td>
                <td class="center">{{ $r->station }}</td>
                <td class="center">{{ $r->method }}</td>
                <td class="center">{{ $r->inspector }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="10" class="center">No inspection rows found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    <br>
    <table style="width:100%; border-collapse:separate; border-spacing:0;">
        <tr>
            <td style="border:0; padding:2px 0;"> </td>
        </tr>
        <tr class="ghost-row">
            <td><strong>#CNC OPS:</strong><span style="display:inline-block; border-bottom:1px solid #000; width:80px; text-align:center;">{{ $header['operation'] }} Operations</span></td>
            <td><strong>SAMPLING REQ:</strong><span style="display:inline-block; border-bottom:1px solid #000; width:80px; text-align:center;">{{ $header['sampling'] }}</span></td>
            <td colspan="2"><strong>FAI/IPI QTY:</strong><span style="display:inline-block; border-bottom:1px solid #000; width:80px; text-align:center;">{{ $header['total_fai'] }} FAI / {{ $header['total_ipi'] }} IPI</span></td>
            <td colspan="2"><strong>FINAL INSP QTY:</strong><span style="display:inline-block; border-bottom:1px solid #000; width:80px; text-align:center;"></span></td>
            <td colspan="2"><strong>CMPLT.INI & DATE:</strong><span style="display:inline-block; border-bottom:1px solid #000; width:80px; text-align:center;"></span></td>
        </tr>
    </table>


</body>

</html>