{{-- resources/views/qa/faisummary/faisummary_summarypdf.blade.php --}}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>FAI / IPI Summary</title>
    <style>
        @page {
            margin: 30px 18px 22px 18px;
        }

        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            color: #111;
            font-size: 11px;
        }

        .h1 {
            font-size: 16px;
            font-weight: 700;
            margin: 0 0 6px;
        }

        .small {
            font-size: 10px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta td {
            padding: 4px 6px;
            border: 1px solid #333;
        }

        /* Tabla de datos */
        .grid {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .grid thead th {
            background: #f1f1f1;
            font-weight: 700;
            border: 1px solid #333;
            padding: 6px 6px;
        }

        .grid td {
            border: 1px solid #333;
            padding: 5px 6px;
            vertical-align: top;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }

        /* Anchos aproximados por columna (14 cols) */
        .w-date {
            width: 9%;
        }

        .w-part {
            width: 14%;
        }

        .w-job {
            width: 7%;
        }

        .w-type {
            width: 5%;
        }

        .w-op {
            width: 6%;
        }

        .w-operator {
            width: 8%;
        }

        .w-result {
            width: 7%;
        }

        .w-sbis {
            width: 12%;
        }

        .w-obs {
            width: 16%;
        }

        .w-station {
            width: 6%;
        }

        .w-method {
            width: 6%;
        }

        .w-qtyinsp {
            width: 6%;
        }

        .w-inspector {
            width: 8%;
        }

        .w-location {
            width: 6%;
        }

        /* Repetir thead en cada página */
        thead {
            display: table-header-group;
        }

        tfoot {
            display: table-row-group;
        }

        tr {
            page-break-inside: avoid;
        }

        /* Resumen FAI/IPI para Dompdf (colores planos) */
        .summary-box {
            padding: 8px;
            border-radius: 4px;
            margin: 8px 0 10px 0;
            border: 1px solid #333;
            width: 70%;
        }

        .summary-ok {
            background: #f1f1f1;
            color: #000;
        }

        .summary-warn {
            background: #fdf2f2;
            color: #000;
        }

        .summary-body {
            font-size: 10px;
            line-height: 1.35;
        }

        .badge-pill {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 10px;
            font-size: 10px;
            font-weight: 700;
        }

        .badge-pass {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }

        .badge-fail {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
    </style>
</head>

<body>

    @php
    $generatedAt = $generatedAt ?? now();
    $userName = $user->name ?? 'System';

    // 📊 resumen que viene del controlador, basado SOLO en las filas del PDF
    $total = $pdfStats['total'] ?? 0;
    $pass = $pdfStats['pass'] ?? 0;
    $fail = $pdfStats['fail'] ?? 0;
    $rate = $pdfStats['rate'] ?? 0;
    @endphp

    {{-- Encabezado resumen --}}
    <table class="meta" style="margin-bottom:8px; width:100%; table-layout:fixed; border-collapse:collapse;">
        <colgroup>
            <col style="width: 35%;">
            <col style="width: 35%;">
            <col style="width: 30%;">
        </colgroup>
        <tr>
            <td>
                <div class="h1">FAI / IPI Summary Report</div>
                <div class="small">Generated by Quality Inspection</div>
            </td>
            <td>
                <strong>Period:</strong>
                @if($month && $year)
                {{ \Carbon\Carbon::create()->month($month)->format('F') }} {{ $year }}
                @elseif($year)
                Year {{ $year }}
                @else
                All dates
                @endif
                <br>
                <strong>Total Inspections:</strong> {{ $total }}<br>
                <strong>Pass:</strong> {{ $pass }} |
                <strong>No Pass:</strong> {{ $fail }} |
                <strong>Pass Rate:</strong> {{ $rate }}%
            </td>
            <td>
                <div class="small">
                    <strong>Printed:</strong> {{ $generatedAt->format('m/d/Y H:i') }}<br>
                    <strong>User:</strong> {{ $userName }}
                </div>
            </td>
        </tr>
    </table>

    {{-- Caja de resumen visual --}}
    <div class="summary-box {{ $rate >= 95 ? 'summary-ok' : 'summary-warn' }}">
        <div class="summary-body">
            <strong>Summary:</strong>
            @if($total === 0)
            No inspections found for the selected filters.
            @else
            Out of {{ $total }} inspections,
            <span class="badge-pill badge-pass">{{ $pass }} PASS</span> and
            <span class="badge-pill badge-fail">{{ $fail }} NO PASS</span>.
            Overall pass rate: <strong>{{ $rate }}%</strong>.
            @endif
        </div>
    </div>

    {{-- Tabla de registros --}}
    <table class="grid">
        <thead>
            <tr>
                <th class="center w-date">Date</th>
                <th class="center w-part">Part/Revision</th>
                <th class="center w-job">Job</th>
                <th class="center w-type">Type</th>
                <th class="center w-op">Op</th>
                <th class="center w-operator">Operator</th>
                <th class="center w-result">Result</th>
                <th class="center w-sbis">SB/IS</th>
                <th class="center w-obs">Observation</th>
                <th class="center w-station">Station</th>
                <th class="center w-method">Method</th>
                <th class="center w-qtyinsp">Qty Insp</th>
                <th class="center w-inspector">Inspector</th>
                <th class="center w-location">Location</th>
            </tr>
        </thead>
        <tbody>
            @php
            $tz = config('app.timezone', 'UTC');
            @endphp

            @forelse($inspections as $r)
            @php
            $dtCreated = $r->created_at
            ? $r->created_at->copy()->setTimezone($tz)
            : null;

            $isPass = strtolower(trim((string)$r->results)) === 'pass';
            @endphp
            <tr>
                <td class="center">
                    {{ $dtCreated?->format('m/d/Y') }}
                    @if($dtCreated)
                    <br>{{ $dtCreated->format('H:i') }}
                    @endif
                </td>
                <td>{{ $r->orderSchedule->PN ?? '' }}</td>
                <td class="center">{{ $r->orderSchedule->work_id ?? '' }}</td>
                <td class="center">{{ strtoupper($r->insp_type) }}</td>
                <td class="center">{{ $r->operation }}</td>
                <td>{{ $r->operator }}</td>
                <td class="center">
                    {{ $isPass ? 'Pass' : 'No Pass' }}
                </td>
                <td>{{ $r->sb_is }}</td>
                <td>{{ $r->observation }}</td>
                <td class="center">{{ $r->station }}</td>
                <td class="center">{{ $r->method }}</td>
                <td class="right">{{ $r->qty_pcs }}</td>
                <td>{{ $r->inspector }}</td>
                <td class="center">{{ $r->loc_inspection }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="14" class="center">No inspection rows found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

</body>

</html>