<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>FAI {{ $header['work_id'] }}</title>
    <style>
        @page {
            margin: 18px 18px 22px 18px;
        }

        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            color: #111;
            font-size: 11px;
        }

        /* Encabezado */
        .h1 {
            font-size: 16px;
            font-weight: 700;
            margin: 0 0 6px;
        }

        .small {
            font-size: 10px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta td {
            padding: 4px 6px;
            border: 1px solid #333;
        }

        /* Tabla de datos */
        .grid {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .grid thead th {
            background: #f1f1f1;
            font-weight: 700;
            border: 1px solid #333;
            padding: 6px 6px;
        }

        .grid td {
            border: 1px solid #333;
            padding: 5px 6px;
            vertical-align: top;
        }

        .center {
            text-align: center;
        }

        .w-date {
            width: 12%;
        }

        .w-type {
            width: 10%;
        }

        .w-op {
            width: 12%;
        }

        .w-operator {
            width: 12%;
        }

        .w-results {
            width: 9%;
        }

        .w-sbis {
            width: 10%;
        }

        .w-obs {
            width: 18%;
        }

        .w-station {
            width: 9%;
        }

        .w-method {
            width: 8%;
        }

        /* Repetir thead en cada página */
        thead {
            display: table-header-group;
        }

        tfoot {
            display: table-row-group;
        }

        tr {
            page-break-inside: avoid;
        }

        /* Estilo “input” visual como tu UI */
        .cellbox {
            background: #f7f9fb;
            border: 1px solid #d7dde5;
            padding: 3px 5px;
            border-radius: 3px;
        }

   
    </style>
</head>

<body>

    {{-- Encabezado --}}
    <table class="meta" style="margin-bottom:8px;">
        <tr>
            <td colspan="3">
                <div class="h1">FAI / IPI Inspection</div>
                <div class="small">Generated by Inspection</div>
            </td>
            <td><strong>WO#</strong><br>{{ $header['work_id'] }}</td>
            <td><strong>PN</strong><br>{{ $header['pn'] }}</td>
            <td><strong>CO#</strong><br>{{ $header['co'] }}</td>
            <td><strong>Loc</strong><br>{{ $header['location'] }}</td>
            <td><strong>WO Qty</strong><br>{{ $header['wo_qty'] }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>CO QTY:</strong> {{ $header['qty'] }}</td>
            <td colspan="2"><strong>DUE DATE:</strong> {{ $header['due_date'] ? \Carbon\Carbon::parse($header['due_date'])->format('m/d/Y') : '' }}</td>
            <td><strong>CO#:</strong> {{ $header['co'] }}</td>
            <td><strong>CUST PO#:</strong> {{ $header['cust_po'] }}</td>
            <td><strong>WO QTY#:</strong> {{ $header['wo_qty'] }}</td>
            <td><strong>QC INSP PACKET</strong></td>
        </tr>

        <tr>
            <td colspan="8"><strong>Description:</strong> {{ $header['description'] }}</td>
        </tr>
    </table>

    {{-- Tabla de filas UNO A UNO --}}
    <table class="grid">
        <thead>
            <tr>
                <th class="center w-date">DATE</th>
                <th class="center w-type">INSP TYPE</th>
                <th class="center w-op">OPERATION</th>
                <th class="center w-operator">OPERATOR</th>
                <th class="center w-results">RESULTS</th>
                <th class="center w-sbis">SB/IS</th>
                <th class="center w-obs">OBSERVATION</th>
                <th class="center w-station">STATION</th>
                <th class="center w-method">METHOD</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $r)
            <tr>
                <td class="center">{{ \Carbon\Carbon::parse($r->date)->format('m/d/Y') }}</td>
                <td class="center">{{ strtoupper($r->insp_type) }}</td>
                <td class="center">{{ $r->operation }}</td>
                <td class="center">
                    <{{ $r->operator }}< /td>
                <td class="center">
                    @php $res = strtolower((string)$r->results); @endphp
                    {{ $res === 'pass' ? 'Pass' : ($res === 'fail' ? 'Fail' : strtoupper($r->results)) }}
                </td>
                <td class="">{{ $r->sb_is }}</td>
                <td class="">{{ $r->observation }}</td>
                <td class="center">{{ $r->station }}</td>
                <td class="center">{{ $r->method }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="center">No inspection rows found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

</body>

</html>